server:
  port: 8010
spring: 
  freemarker:
    suffix: .html
    template-loader-path: classpath:/templates
    content-type: text/html; charset=utf-8  
  profiles:
    active: prod
  mvc:
    static-path-pattern: /resources/**
    
    


   
