server:
  port: 8010
spring: 
  freemarker:
    suffix: .html
    template-loader-path: classpath:/templates
    content-type: text/html; charset=utf-8  
  profiles:
    active: prod
  mvc:
    static-path-pattern: /resources/**
  datasource: 
    url: jdbc:mysql://172.16.140.130:3306/senyint_sick_platform?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    xa:
      properties:
          useInformationSchema: true
    
 
    
    


   
