server:
  port: 8086
spring: 
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates
    content-type: text/html; charset=utf-8  
  profiles:
    active: prod
  mvc:
    static-path-pattern: /resources/**

    
